/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ACSOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SCORE"
      | "MIN_SCORE"
      | "SCORE_VALIDITY"
      | "agentScores"
      | "computeDigest"
      | "getScore"
      | "hasValidScore"
      | "invalidateScore"
      | "oracleSigner"
      | "owner"
      | "renounceOwnership"
      | "setOracleSigner"
      | "setScore"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebugDigest"
      | "OracleSignerChanged"
      | "OwnershipTransferred"
      | "ScoreUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_SCORE", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_SCORE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SCORE_VALIDITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentScores",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeDigest",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getScore", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasValidScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "invalidateScore",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleSigner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setOracleSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setScore",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_SCORE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_SCORE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SCORE_VALIDITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasValidScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invalidateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOracleSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DebugDigestEvent {
  export type InputTuple = [
    digest: BytesLike,
    recovered: AddressLike,
    expected: AddressLike
  ];
  export type OutputTuple = [
    digest: string,
    recovered: string,
    expected: string
  ];
  export interface OutputObject {
    digest: string;
    recovered: string;
    expected: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleSignerChangedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    agentDID: BytesLike,
    score: BigNumberish,
    timestamp: BigNumberish,
    expiry: BigNumberish
  ];
  export type OutputTuple = [
    agentDID: string,
    score: bigint,
    timestamp: bigint,
    expiry: bigint
  ];
  export interface OutputObject {
    agentDID: string;
    score: bigint;
    timestamp: bigint;
    expiry: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ACSOracle extends BaseContract {
  connect(runner?: ContractRunner | null): ACSOracle;
  waitForDeployment(): Promise<this>;

  interface: ACSOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SCORE: TypedContractMethod<[], [bigint], "view">;

  MIN_SCORE: TypedContractMethod<[], [bigint], "view">;

  SCORE_VALIDITY: TypedContractMethod<[], [bigint], "view">;

  agentScores: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string] & {
        score: bigint;
        timestamp: bigint;
        expiry: bigint;
        signature: string;
      }
    ],
    "view"
  >;

  computeDigest: TypedContractMethod<
    [
      agentDID: BytesLike,
      score: BigNumberish,
      timestamp: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;

  getScore: TypedContractMethod<
    [agentDID: BytesLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        timestamp: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;

  hasValidScore: TypedContractMethod<[agentDID: BytesLike], [boolean], "view">;

  invalidateScore: TypedContractMethod<
    [agentDID: BytesLike],
    [void],
    "nonpayable"
  >;

  oracleSigner: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setOracleSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setScore: TypedContractMethod<
    [
      agentDID: BytesLike,
      score: BigNumberish,
      timestamp: BigNumberish,
      expiry: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SCORE_VALIDITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentScores"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, string] & {
        score: bigint;
        timestamp: bigint;
        expiry: bigint;
        signature: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "computeDigest"
  ): TypedContractMethod<
    [
      agentDID: BytesLike,
      score: BigNumberish,
      timestamp: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<
    [agentDID: BytesLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        timestamp: bigint;
        expiry: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasValidScore"
  ): TypedContractMethod<[agentDID: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "invalidateScore"
  ): TypedContractMethod<[agentDID: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "oracleSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracleSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setScore"
  ): TypedContractMethod<
    [
      agentDID: BytesLike,
      score: BigNumberish,
      timestamp: BigNumberish,
      expiry: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DebugDigest"
  ): TypedContractEvent<
    DebugDigestEvent.InputTuple,
    DebugDigestEvent.OutputTuple,
    DebugDigestEvent.OutputObject
  >;
  getEvent(
    key: "OracleSignerChanged"
  ): TypedContractEvent<
    OracleSignerChangedEvent.InputTuple,
    OracleSignerChangedEvent.OutputTuple,
    OracleSignerChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;

  filters: {
    "DebugDigest(bytes32,address,address)": TypedContractEvent<
      DebugDigestEvent.InputTuple,
      DebugDigestEvent.OutputTuple,
      DebugDigestEvent.OutputObject
    >;
    DebugDigest: TypedContractEvent<
      DebugDigestEvent.InputTuple,
      DebugDigestEvent.OutputTuple,
      DebugDigestEvent.OutputObject
    >;

    "OracleSignerChanged(address,address)": TypedContractEvent<
      OracleSignerChangedEvent.InputTuple,
      OracleSignerChangedEvent.OutputTuple,
      OracleSignerChangedEvent.OutputObject
    >;
    OracleSignerChanged: TypedContractEvent<
      OracleSignerChangedEvent.InputTuple,
      OracleSignerChangedEvent.OutputTuple,
      OracleSignerChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ScoreUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
  };
}
