/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LendingPool {
  export type LoanStruct = {
    id: BigNumberish;
    borrowerDID: BytesLike;
    lender: AddressLike;
    principalToken: AddressLike;
    principalAmount: BigNumberish;
    interestRateBps: BigNumberish;
    startTime: BigNumberish;
    maturity: BigNumberish;
    collateralToken: AddressLike;
    collateralAmount: BigNumberish;
    status: BigNumberish;
    repaidAmount: BigNumberish;
    liquidatedAmount: BigNumberish;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrowerDID: string,
    lender: string,
    principalToken: string,
    principalAmount: bigint,
    interestRateBps: bigint,
    startTime: bigint,
    maturity: bigint,
    collateralToken: string,
    collateralAmount: bigint,
    status: bigint,
    repaidAmount: bigint,
    liquidatedAmount: bigint
  ] & {
    id: bigint;
    borrowerDID: string;
    lender: string;
    principalToken: string;
    principalAmount: bigint;
    interestRateBps: bigint;
    startTime: bigint;
    maturity: bigint;
    collateralToken: string;
    collateralAmount: bigint;
    status: bigint;
    repaidAmount: bigint;
    liquidatedAmount: bigint;
  };
}

export interface LendingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LIQUIDATION_PENALTY_BPS"
      | "LIQUIDATION_THRESHOLD_BPS"
      | "MAX_INTEREST_RATE_BPS"
      | "MAX_LOAN_DURATION"
      | "MIN_INTEREST_RATE_BPS"
      | "MIN_LOAN_DURATION"
      | "PROTOCOL_FEE_BPS"
      | "acsOracle"
      | "baseToken"
      | "borrowerAddresses"
      | "borrowerLoans"
      | "claimPrincipal"
      | "collateralManager"
      | "createLoan"
      | "createLoanWithCollateral"
      | "emergencyWithdraw"
      | "getBaseTokenBalance"
      | "getBorrowerAddress"
      | "getBorrowerLoans"
      | "getLenderLoans"
      | "getLoan"
      | "getOutstanding"
      | "handleDefault"
      | "lenderLoans"
      | "liquidateLoan"
      | "loanCounter"
      | "loans"
      | "owner"
      | "paused"
      | "renounceOwnership"
      | "repayLoan"
      | "setACSOracle"
      | "setCollateralManager"
      | "setPaused"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanLiquidated"
      | "LoanRepaid"
      | "OwnershipTransferred"
      | "PoolPaused"
      | "PrincipalClaimed"
      | "ProtocolFeeCollected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LIQUIDATION_PENALTY_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATION_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_INTEREST_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LOAN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_INTEREST_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LOAN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "acsOracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "baseToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowerAddresses",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoans",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPrincipal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoanWithCollateral",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoans",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutstanding",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setACSOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCollateralManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LIQUIDATION_PENALTY_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATION_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_INTEREST_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LOAN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_INTEREST_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LOAN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acsOracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPrincipal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createLoanWithCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOutstanding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setACSOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCollateralManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowerDID: BytesLike,
    lender: AddressLike,
    principalToken: AddressLike,
    principalAmount: BigNumberish,
    interestRateBps: BigNumberish,
    maturity: BigNumberish,
    collateralToken: AddressLike,
    collateralAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowerDID: string,
    lender: string,
    principalToken: string,
    principalAmount: bigint,
    interestRateBps: bigint,
    maturity: bigint,
    collateralToken: string,
    collateralAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowerDID: string;
    lender: string;
    principalToken: string;
    principalAmount: bigint;
    interestRateBps: bigint;
    maturity: bigint;
    collateralToken: string;
    collateralAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowerDID: BytesLike,
    outstandingDebt: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowerDID: string,
    outstandingDebt: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowerDID: string;
    outstandingDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanLiquidatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowerDID: BytesLike,
    liquidator: AddressLike,
    collateralSeized: BigNumberish,
    debtCovered: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowerDID: string,
    liquidator: string,
    collateralSeized: bigint,
    debtCovered: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowerDID: string;
    liquidator: string;
    collateralSeized: bigint;
    debtCovered: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowerDID: BytesLike,
    principalAmount: BigNumberish,
    interestAmount: BigNumberish,
    protocolFee: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowerDID: string,
    principalAmount: bigint,
    interestAmount: bigint,
    protocolFee: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowerDID: string;
    principalAmount: bigint;
    interestAmount: bigint;
    protocolFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrincipalClaimedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrowerDID: BytesLike,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrowerDID: string,
    borrower: string,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrowerDID: string;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeCollectedEvent {
  export type InputTuple = [loanId: BigNumberish, feeAmount: BigNumberish];
  export type OutputTuple = [loanId: bigint, feeAmount: bigint];
  export interface OutputObject {
    loanId: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingPool extends BaseContract {
  connect(runner?: ContractRunner | null): LendingPool;
  waitForDeployment(): Promise<this>;

  interface: LendingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LIQUIDATION_PENALTY_BPS: TypedContractMethod<[], [bigint], "view">;

  LIQUIDATION_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_INTEREST_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_LOAN_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_INTEREST_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_LOAN_DURATION: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  acsOracle: TypedContractMethod<[], [string], "view">;

  baseToken: TypedContractMethod<[], [string], "view">;

  borrowerAddresses: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  borrowerLoans: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  claimPrincipal: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  collateralManager: TypedContractMethod<[], [string], "view">;

  createLoan: TypedContractMethod<
    [
      borrowerDID: BytesLike,
      borrowerAddress: AddressLike,
      principalAmount: BigNumberish,
      interestRateBps: BigNumberish,
      duration: BigNumberish,
      collateralToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  createLoanWithCollateral: TypedContractMethod<
    [
      borrowerDID: BytesLike,
      borrowerAddress: AddressLike,
      principalAmount: BigNumberish,
      interestRateBps: BigNumberish,
      duration: BigNumberish,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBaseTokenBalance: TypedContractMethod<[], [bigint], "view">;

  getBorrowerAddress: TypedContractMethod<
    [borrowerDID: BytesLike],
    [string],
    "view"
  >;

  getBorrowerLoans: TypedContractMethod<
    [borrowerDID: BytesLike],
    [bigint[]],
    "view"
  >;

  getLenderLoans: TypedContractMethod<
    [lender: AddressLike],
    [bigint[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [LendingPool.LoanStructOutput],
    "view"
  >;

  getOutstanding: TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;

  handleDefault: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  lenderLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  liquidateLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  loanCounter: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrowerDID: string;
        lender: string;
        principalToken: string;
        principalAmount: bigint;
        interestRateBps: bigint;
        startTime: bigint;
        maturity: bigint;
        collateralToken: string;
        collateralAmount: bigint;
        status: bigint;
        repaidAmount: bigint;
        liquidatedAmount: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  setACSOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setCollateralManager: TypedContractMethod<
    [newManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LIQUIDATION_PENALTY_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQUIDATION_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_INTEREST_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LOAN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_INTEREST_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LOAN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acsOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowerAddresses"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "borrowerLoans"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimPrincipal"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      borrowerDID: BytesLike,
      borrowerAddress: AddressLike,
      principalAmount: BigNumberish,
      interestRateBps: BigNumberish,
      duration: BigNumberish,
      collateralToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createLoanWithCollateral"
  ): TypedContractMethod<
    [
      borrowerDID: BytesLike,
      borrowerAddress: AddressLike,
      principalAmount: BigNumberish,
      interestRateBps: BigNumberish,
      duration: BigNumberish,
      collateralToken: AddressLike,
      collateralAmount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBaseTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBorrowerAddress"
  ): TypedContractMethod<[borrowerDID: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getBorrowerLoans"
  ): TypedContractMethod<[borrowerDID: BytesLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLenderLoans"
  ): TypedContractMethod<[lender: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [LendingPool.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutstanding"
  ): TypedContractMethod<[loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "handleDefault"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lenderLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "liquidateLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loanCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrowerDID: string;
        lender: string;
        principalToken: string;
        principalAmount: bigint;
        interestRateBps: bigint;
        startTime: bigint;
        maturity: bigint;
        collateralToken: string;
        collateralAmount: bigint;
        status: bigint;
        repaidAmount: bigint;
        liquidatedAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setACSOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCollateralManager"
  ): TypedContractMethod<[newManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanLiquidated"
  ): TypedContractEvent<
    LoanLiquidatedEvent.InputTuple,
    LoanLiquidatedEvent.OutputTuple,
    LoanLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolPaused"
  ): TypedContractEvent<
    PoolPausedEvent.InputTuple,
    PoolPausedEvent.OutputTuple,
    PoolPausedEvent.OutputObject
  >;
  getEvent(
    key: "PrincipalClaimed"
  ): TypedContractEvent<
    PrincipalClaimedEvent.InputTuple,
    PrincipalClaimedEvent.OutputTuple,
    PrincipalClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeCollected"
  ): TypedContractEvent<
    ProtocolFeeCollectedEvent.InputTuple,
    ProtocolFeeCollectedEvent.OutputTuple,
    ProtocolFeeCollectedEvent.OutputObject
  >;

  filters: {
    "LoanCreated(uint256,bytes32,address,address,uint256,uint256,uint256,address,uint256)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256,bytes32,uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanLiquidated(uint256,bytes32,address,uint256,uint256)": TypedContractEvent<
      LoanLiquidatedEvent.InputTuple,
      LoanLiquidatedEvent.OutputTuple,
      LoanLiquidatedEvent.OutputObject
    >;
    LoanLiquidated: TypedContractEvent<
      LoanLiquidatedEvent.InputTuple,
      LoanLiquidatedEvent.OutputTuple,
      LoanLiquidatedEvent.OutputObject
    >;

    "LoanRepaid(uint256,bytes32,uint256,uint256,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolPaused(bool)": TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;
    PoolPaused: TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;

    "PrincipalClaimed(uint256,bytes32,address,uint256)": TypedContractEvent<
      PrincipalClaimedEvent.InputTuple,
      PrincipalClaimedEvent.OutputTuple,
      PrincipalClaimedEvent.OutputObject
    >;
    PrincipalClaimed: TypedContractEvent<
      PrincipalClaimedEvent.InputTuple,
      PrincipalClaimedEvent.OutputTuple,
      PrincipalClaimedEvent.OutputObject
    >;

    "ProtocolFeeCollected(uint256,uint256)": TypedContractEvent<
      ProtocolFeeCollectedEvent.InputTuple,
      ProtocolFeeCollectedEvent.OutputTuple,
      ProtocolFeeCollectedEvent.OutputObject
    >;
    ProtocolFeeCollected: TypedContractEvent<
      ProtocolFeeCollectedEvent.InputTuple,
      ProtocolFeeCollectedEvent.OutputTuple,
      ProtocolFeeCollectedEvent.OutputObject
    >;
  };
}
